FROM python:3.7-alpine

RUN apk add make gcc musl-dev

WORKDIR /project

COPY requirements.txt /project/
COPY requirements-test.txt /project/

RUN pip install -r requirements-test.txt
RUN pip install --upgrade pip

COPY . /project

RUN make venv

CMD ["make", "test"]
